FROM golang:alpine

RUN mkdir /app

WORKDIR ./app

ADD go.mod .

ADD go.sum .

RUN go mod download

ADD . .

RUN go get github.com/subramanya812/crud-operation

EXPOSE 8080

ENTRYPOINT crud-operation --build="go build main.go" --command=./main
